### ISSUE TITLE
Precompile to es5 to be support with create-react-app

### ISSUE THREAD

**Issue by aeciolevy** [caiogondim/tubo.js#28]
Failed to build with react-scripts:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by caiogondim** [comment]
Should be fixed by https://github.com/caiogondim/tubo.js/pull/29

**Comment by caiogondim** [comment]
New version published to npm already.
